# Generated by Django 4.2.4 on 2023-09-26 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todo_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="target_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 26, 6, 49, 39, 915639, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
